### ISSUE TITLE
[Task] Make XCC works again on legacy OSs

### ISSUE THREAD

**Issue by CNAmira** [CNAmira/xcc#1]
## Propose
New commits have broken up compatibility to legacy OSs such as Windows 98, I'm willing to port it back to those OSs without breaking new features.
## Task
- [ ] Replace `boost` with `C++ STL` as `boost` has dropped Win9X support for a very long time, but most C++ 17 features is available when using MinGW32.
- [ ] Replace `MFC` with `WTL`.
- [ ] Make it compiles with MinGW32.
